package com.bluetoothseclab

import android.content.Intent
import android.os.Bundle
import androidx.activity.OnBackPressedCallback
import androidx.appcompat.app.AppCompatActivity
import com.bluetoothseclab.databinding.ActivitySecurityReportBinding
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class SecurityReportActivity : AppCompatActivity() {

    private lateinit var binding: ActivitySecurityReportBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivitySecurityReportBinding.inflate(layoutInflater)
        setContentView(binding.root)

        supportActionBar?.setDisplayHomeAsUpEnabled(true)

        onBackPressedDispatcher.addCallback(this, object : OnBackPressedCallback(true) {
            override fun handleOnBackPressed() {
                finish()
            }
        })

        val deviceName = intent.getStringExtra("report_device_name") ?: "Unknown"
        val deviceAddress = intent.getStringExtra("report_device_address") ?: ""
        val services = intent.getStringArrayExtra("report_services") ?: emptyArray()
        val issueCount = intent.getIntExtra("report_issue_count", 0)
        val timestamp = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date())

        binding.tvReportDevice.text = "Device: $deviceName ($deviceAddress)"
        binding.tvReportTimestamp.text = "Assessment Time: $timestamp"

        val report = buildString {
            appendLine("========================================")
            appendLine("  BLUETOOTH SECURITY ASSESSMENT REPORT")
            appendLine("========================================")
            appendLine()
            appendLine("Device: $deviceName")
            appendLine("Address: $deviceAddress")
            appendLine("Timestamp: $timestamp")
            appendLine()

            // Environment info
            appendLine("--- Assessment Environment ---")
            appendLine("Tool: BT Security Lab v1.1")
            appendLine("Platform: Android")
            appendLine("Type: Passive scanning (no active exploitation)")
            appendLine()

            // Services
            appendLine("--- Discovered Services ($services.size) ---")
            if (services.isEmpty()) {
                appendLine("  No SDP records retrieved")
            } else {
                services.forEach { appendLine("  • $it") }
            }
            appendLine()

            // Risk summary
            appendLine("--- Security Risk Summary ---")
            appendLine("Issues found: $issueCount")
            appendLine()

            // Findings
            appendLine("--- Detailed Findings ---")
            if (issueCount == 0) {
                appendLine("  No security issues detected during passive assessment.")
                appendLine("  Note: This does not guarantee the device is secure.")
                appendLine("  Active testing (with authorization) may reveal additional issues.")
            } else {
                appendLine("  $issueCount potential issue(s) identified.")
                appendLine("  Review each issue against your threat model.")
                appendLine("  Verify findings with authorized active testing.")
            }
            appendLine()

            // Recommendations
            appendLine("--- Recommendations ---")
            appendLine("1. Ensure Bluetooth firmware is up to date")
            appendLine("2. Disable unused Bluetooth profiles/services")
            appendLine("3. Use secure pairing (LE Secure Connections)")
            appendLine("4. Enable only when needed")
            appendLine("5. Review bonded devices regularly")
            appendLine()

            // Legal
            appendLine("--- Legal Notice ---")
            appendLine("This assessment was performed on authorized devices.")
            appendLine("Do not act on findings without explicit permission.")
            appendLine("For educational and research purposes only.")
            appendLine()

            appendLine("========================================")
            appendLine("  Report generated by BT Security Lab")
            appendLine("  Authorized testing only")
            appendLine("========================================")
        }

        binding.tvReportContent.text = report

        binding.btnShareReport.setOnClickListener {
            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_SUBJECT, "BT Security Report - $deviceName")
                putExtra(Intent.EXTRA_TEXT, report)
            }
            startActivity(Intent.createChooser(shareIntent, "Share Report"))
        }
    }

    override fun onSupportNavigateUp(): Boolean {
        finish()
        return true
    }
}
